/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-color": "var(--primary-color)",
        "secondary-color": "var(--secondary-color)",
        "success-color": "var(--success-color)",
        "warning-color": "var(--warning-color)",
        "info-color": "var(--info-color)",
        "danger-color": "var(--danger-color)",
        "text-primary-color": "var(--text-primary-color)",
        "header-color": "var(--header-color)",
        "header-text-color": "var(--header-text-color)",
        "background-color": "var(--background-color)",
        "primary-color-50": "rgba(var(--primary-color-rgb), 0.05)",
        "primary-color-100": "rgba(var(--primary-color-rgb), 0.1)",
        "primary-color-200": "rgba(var(--primary-color-rgb), 0.2)",
        "primary-color-300": "rgba(var(--primary-color-rgb), 0.3)",
        "primary-color-400": "rgba(var(--primary-color-rgb), 0.4)",
        "primary-color-500": "rgba(var(--primary-color-rgb), 0.5)",
        "primary-color-600": "rgba(var(--primary-color-rgb), 0.6)",
        "primary-color-700": "rgba(var(--primary-color-rgb), 0.7)",
        "primary-color-800": "rgba(var(--primary-color-rgb), 0.8)",
        "primary-color-900": "rgba(var(--primary-color-rgb), 0.9)",
        "primary-color-950": "rgba(var(--primary-color-rgb), 0.95)",
        "secondary-color-50": "rgba(var(--secondary-color-rgb), 0.05)",
        "secondary-color-100": "rgba(var(--secondary-color-rgb), 0.1)",
        "secondary-color-200": "rgba(var(--secondary-color-rgb), 0.2)",
        "secondary-color-300": "rgba(var(--secondary-color-rgb), 0.3)",
        "secondary-color-400": "rgba(var(--secondary-color-rgb), 0.4)",
        "secondary-color-500": "rgba(var(--secondary-color-rgb), 0.5)",
        "secondary-color-600": "rgba(var(--secondary-color-rgb), 0.6)",
        "secondary-color-700": "rgba(var(--secondary-color-rgb), 0.7)",
        "secondary-color-800": "rgba(var(--secondary-color-rgb), 0.8)",
        "secondary-color-900": "rgba(var(--secondary-color-rgb), 0.9)",
        "secondary-color-950": "rgba(var(--secondary-color-rgb), 0.95)",
        "success-color-50": "rgba(var(--success-color-rgb), 0.05)",
        "success-color-100": "rgba(var(--success-color-rgb), 0.1)",
        "success-color-200": "rgba(var(--success-color-rgb), 0.2)",
        "success-color-300": "rgba(var(--success-color-rgb), 0.3)",
        "success-color-400": "rgba(var(--success-color-rgb), 0.4)",
        "success-color-500": "rgba(var(--success-color-rgb), 0.5)",
        "success-color-600": "rgba(var(--success-color-rgb), 0.6)",
        "success-color-700": "rgba(var(--success-color-rgb), 0.7)",
        "success-color-800": "rgba(var(--success-color-rgb), 0.8)",
        "success-color-900": "rgba(var(--success-color-rgb), 0.9)",
        "success-color-950": "rgba(var(--success-color-rgb), 0.95)",
        "warning-color-50": "rgba(var(--warning-color-rgb), 0.05)",
        "warning-color-100": "rgba(var(--warning-color-rgb), 0.1)",
        "warning-color-200": "rgba(var(--warning-color-rgb), 0.2)",
        "warning-color-300": "rgba(var(--warning-color-rgb), 0.3)",
        "warning-color-400": "rgba(var(--warning-color-rgb), 0.4)",
        "warning-color-500": "rgba(var(--warning-color-rgb), 0.5)",
        "warning-color-600": "rgba(var(--warning-color-rgb), 0.6)",
        "warning-color-700": "rgba(var(--warning-color-rgb), 0.7)",
        "warning-color-800": "rgba(var(--warning-color-rgb), 0.8)",
        "warning-color-900": "rgba(var(--warning-color-rgb), 0.9)",
        "warning-color-950": "rgba(var(--warning-color-rgb), 0.95)",
        "info-color-50": "rgba(var(--info-color-rgb), 0.05)",
        "info-color-100": "rgba(var(--info-color-rgb), 0.1)",
        "info-color-200": "rgba(var(--info-color-rgb), 0.2)",
        "info-color-300": "rgba(var(--info-color-rgb), 0.3)",
        "info-color-400": "rgba(var(--info-color-rgb), 0.4)",
        "info-color-500": "rgba(var(--info-color-rgb), 0.5)",
        "info-color-600": "rgba(var(--info-color-rgb), 0.6)",
        "info-color-700": "rgba(var(--info-color-rgb), 0.7)",
        "info-color-800": "rgba(var(--info-color-rgb), 0.8)",
        "info-color-900": "rgba(var(--info-color-rgb), 0.9)",
        "info-color-950": "rgba(var(--info-color-rgb), 0.95)",
        "danger-color-50": "rgba(var(--danger-color-rgb), 0.05)",
        "danger-color-100": "rgba(var(--danger-color-rgb), 0.1)",
        "danger-color-200": "rgba(var(--danger-color-rgb), 0.2)",
        "danger-color-300": "rgba(var(--danger-color-rgb), 0.3)",
        "danger-color-400": "rgba(var(--danger-color-rgb), 0.4)",
        "danger-color-500": "rgba(var(--danger-color-rgb), 0.5)",
        "danger-color-600": "rgba(var(--danger-color-rgb), 0.6)",
        "danger-color-700": "rgba(var(--danger-color-rgb), 0.7)",
        "danger-color-800": "rgba(var(--danger-color-rgb), 0.8)",
        "danger-color-900": "rgba(var(--danger-color-rgb), 0.9)",
        "danger-color-950": "rgba(var(--danger-color-rgb), 0.95)",
        "text-primary-color-50": "rgba(var(--text-primary-color-rgb), 0.05)",
        "text-primary-color-100": "rgba(var(--text-primary-color-rgb), 0.1)",
        "text-primary-color-200": "rgba(var(--text-primary-color-rgb), 0.2)",
        "text-primary-color-300": "rgba(var(--text-primary-color-rgb), 0.3)",
        "text-primary-color-400": "rgba(var(--text-primary-color-rgb), 0.4)",
        "text-primary-color-500": "rgba(var(--text-primary-color-rgb), 0.5)",
        "text-primary-color-600": "rgba(var(--text-primary-color-rgb), 0.6)",
        "text-primary-color-700": "rgba(var(--text-primary-color-rgb), 0.7)",
        "text-primary-color-800": "rgba(var(--text-primary-color-rgb), 0.8)",
        "text-primary-color-900": "rgba(var(--text-primary-color-rgb), 0.9)",
        "text-primary-color-950": "rgba(var(--text-primary-color-rgb), 0.95)",
        "header-color-50": "rgba(var(--header-color-rgb), 0.05)",
        "header-color-100": "rgba(var(--header-color-rgb), 0.1)",
        "header-color-200": "rgba(var(--header-color-rgb), 0.2)",
        "header-color-300": "rgba(var(--header-color-rgb), 0.3)",
        "header-color-400": "rgba(var(--header-color-rgb), 0.4)",
        "header-color-500": "rgba(var(--header-color-rgb), 0.5)",
        "header-color-600": "rgba(var(--header-color-rgb), 0.6)",
        "header-color-700": "rgba(var(--header-color-rgb), 0.7)",
        "header-color-800": "rgba(var(--header-color-rgb), 0.8)",
        "header-color-900": "rgba(var(--header-color-rgb), 0.9)",
        "header-color-950": "rgba(var(--header-color-rgb), 0.95)",
        "header-text-color-50": "rgba(var(--header-text-color-rgb), 0.05)",
        "header-text-color-100": "rgba(var(--header-text-color-rgb), 0.1)",
        "header-text-color-200": "rgba(var(--header-text-color-rgb), 0.2)",
        "header-text-color-300": "rgba(var(--header-text-color-rgb), 0.3)",
        "header-text-color-400": "rgba(var(--header-text-color-rgb), 0.4)",
        "header-text-color-500": "rgba(var(--header-text-color-rgb), 0.5)",
        "header-text-color-600": "rgba(var(--header-text-color-rgb), 0.6)",
        "header-text-color-700": "rgba(var(--header-text-color-rgb), 0.7)",
        "header-text-color-800": "rgba(var(--header-text-color-rgb), 0.8)",
        "header-text-color-900": "rgba(var(--header-text-color-rgb), 0.9)",
        "header-text-color-950": "rgba(var(--header-text-color-rgb), 0.95)",
        "background-color-50": "rgba(var(--background-color-rgb), 0.05)",
        "background-color-100": "rgba(var(--background-color-rgb), 0.1)",
        "background-color-200": "rgba(var(--background-color-rgb), 0.2)",
        "background-color-300": "rgba(var(--background-color-rgb), 0.3)",
        "background-color-400": "rgba(var(--background-color-rgb), 0.4)",
        "background-color-500": "rgba(var(--background-color-rgb), 0.5)",
        "background-color-600": "rgba(var(--background-color-rgb), 0.6)",
        "background-color-700": "rgba(var(--background-color-rgb), 0.7)",
        "background-color-800": "rgba(var(--background-color-rgb), 0.8)",
        "background-color-900": "rgba(var(--background-color-rgb), 0.9)",
        "background-color-950": "rgba(var(--background-color-rgb), 0.95)",
      },
      fontFamily: {
        brume: ["Brume"],
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
  },
  plugins: [],
};
